### ISSUE TITLE
Any plans for rack 2 support (for Rails 5)?

### ISSUE THREAD

**Issue by andyw8** [eval/rack-pjax#27]
The gem isn't currently compatible with Rails 5 as it needs rack ~> 2.x

**Comment by richardvenneman** [comment]
Unfortunately [rails_admin](https://github.com/sferik/rails_admin) also doesn't work with Rails 5 since it depends on `rack-pjax`.

**Comment by myers** [comment]
@eval I think you can close this one now.

**Comment by mshibuya** [comment]
Thanks 👍
